# T051: Zookeeper Service template
# Phase V - Part C: Production Cloud Deployment
{{- if .Values.zookeeper.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: {{ .Values.global.namespace }}
  labels:
    app: zookeeper
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.zookeeper.service.type }}
  ports:
  - port: {{ .Values.zookeeper.service.port }}
    targetPort: {{ .Values.zookeeper.service.targetPort }}
    protocol: TCP
    name: client
  selector:
    app: zookeeper
---
# Headless service for StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-headless
  namespace: {{ .Values.global.namespace }}
  labels:
    app: zookeeper
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: {{ .Values.zookeeper.service.port }}
    targetPort: {{ .Values.zookeeper.service.targetPort }}
    protocol: TCP
    name: client
  - port: {{ .Values.zookeeper.service.peerPort }}
    targetPort: {{ .Values.zookeeper.service.peerPort }}
    protocol: TCP
    name: peer
  - port: {{ .Values.zookeeper.service.leaderElectionPort }}
    targetPort: {{ .Values.zookeeper.service.leaderElectionPort }}
    protocol: TCP
    name: leader-election
  selector:
    app: zookeeper
{{- end }}
